version: '3.8'

networks:
  plugn-network:
    driver: bridge

services:
  
  mysql:
    image: mysql:5.7.44
    platform: linux/amd64
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=plugn
      - MYSQL_DATABASE=plugn
      - MYSQL_USER=plugnuser
      - MYSQL_PASSWORD=plugn
    #ports:
    #  - "3306:3306"
    networks:
      - plugn-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  app:
    build: 
      context: .
      dockerfile: ./Dockerfile-nginx-local
    container_name: plugn-backend-local
    restart: unless-stopped
    #command:
    #  - /bin/sh
    #  - -c
    #  - |
    #    sleep 5 && \
    #    ./init --env=Dev-Server --overwrite=All && \
    #    ./yii migrate && \
    #    sleep 1 && \
    #    ln -s /etc/nginx/sites-available/basic.conf /etc/nginx/sites-enabled/ && \
    #    service nginx restart  && \
    #    tail -f /dev/null  # Keep container running
    ports:
      - "127.0.0.1:8083:8083" #backend endpoint
      - "127.0.0.1:8082:8082" #store endpoint
      - "127.0.0.1:8081:8081" #vendor dashboard endpoint
      - "127.0.0.1:8084:8084" #crm endpoint
      - "127.0.0.1:8085:8085" #partner endpoint
      - "127.0.0.1:8086:8086" #remail endpoint
      - "127.0.0.1:8087:8087" #shortener endpoint
    volumes:
      - .:/home/ubuntu/plugn
      #- ./nginx/basic.conf:/etc/nginx/sites-available/basic.conf
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - plugn-network

  redis:
    image: redis:6.2.3
  #  ports:
  #    - "7777:7777"
 #     - "6379:6379"
    networks:
      - plugn-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 30
   # command:
   #   - redis-server --port 7777
    volumes:
    - redis-data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: plugn-phpmyadmin-local
    environment:
      PMA_HOST: mysql
      PMA_USER: plugnuser
      PMA_PASSWORD: plugn
    ports:
      - "127.0.0.1:8088:80"
    networks:
      - plugn-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  redis-data:
  mysql-data: 
